language: node_js
node_js:
    - "0.10"
before_install:
    - gem update --system
    - gem install compass
    - npm install -g grunt-cli
    - ./.travis/scripts/install_chrome.sh
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start